site_name: Joe Ganser - Data Technologist, Teacher & Fitness junky
repo_url: https://github.com/JoeGanser
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - header.autohide
    - footer.autohide
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

theme:
  name: material
  #custom_dir: material/.overrides #comment out this line to get rid of those stupid @squidfuckn on Fosstodon links in the header
  features:
    - announce.dismiss
    #- content.action.edit #comment out this to prevent the buttons that show the ability to edit the page
    #- content.action.view #comment out this to prevent the buttons that show the ability to edit the page
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  #- minify: #the minify package has problems with it so its commented out
  #    minify_html: true

# Hooks
hooks:
  - material/.overrides/hooks/translations.py

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV "UA-133341012-1"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JoeGanser
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joe-ganser-aa9b8b132/
   

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: joeganser
      repo: joeganser.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
# Page tree
nav:
  - Home: index.md
  - Curriculum Vitae: curriculum_vitae.md
  - Research Projects:
    - Driven Data Competiton - Predicintg Dengu Fever: research/2022-8-2_dengu.md
    - Big Data For Big Dating - 1st place Tinder Competition: research/2019-4-22-Tinder-Gold;-Big-Data-For-Big-Dating-1st-place-competition.md
    - Predicting Breathing rate with Smart Watch Data: research/2019-4-1-Predicting-Breathing-rate-with-smart-watch-data.md
    - Using Plotly to visualize American Fraud Analytics: research/2019-3-24-Fraud-Analytics.md
    - Superconductors - using material data to predict critical temperature: research/2019-1-26-superconductivity-regression.md
    - Mushroom Data - edible or poisonous?: research/2018-12-15-mushroom-classification.md
    - Real Estate Sales - A basic regression tutorial: research/2018-10-20-AMES-tutorial.md
    - 2017 Bitcoin Bubble - Time series forecasting: research/2017-12-21-Bitcoin-Ethereum-timeseries.md
  - Accomplishments: awards_CV.md
  - Lecture Notes:
    - Stats with Python:
      - Exploratory Data Analysis:
        - Notebook: lectures/stats/eda/eda.md
    - Supervised Learning:
      - Classification part 1:
        - Notebook: lectures/supervised_learning/classification_part1/Classification_part1.md
        - Slides: lectures/supervised_learning/classification_part1/Classification_part1_slides.md
      - Classification part 2:
        - Notebook: lectures/supervised_learning/classification_part2/Classification_part2.md
      - Regression part 1:
        - Notebook: lectures/supervised_learning/Regression_part1/Regression_part1.md
        - Slides: lectures/supervised_learning/Regression_part1/Regression_part1_slides.md
      - Regression part 2:
        - Notebook: lectures/supervised_learning/Regression_part2/Regression_part2.md
        - Slides: lectures/supervised_learning/Regression_part2/Regression_part2_slides.md
      - K-Nearest Neighbors & Decision Trees:
        - Notebook: lectures/supervised_learning/KNN_&_Decision_Trees/KNN_and_Decision_Trees_Notebook.md
        - Slides: lectures/supervised_learning/KNN_&_Decision_Trees/KNN_and_Decision_Trees_Slides.md
    - Unsupervised Learning:
      - DB Scan:
        - Notebook: lectures/unsupervised_learning/db_scan/db_scan_notebook.md
        - Slides: lectures/unsupervised_learning/db_scan/db_scan_slides.md
      - Kmeans:
        - Notebook: lectures/unsupervised_learning/KMeans/KMeans_notebook.md
      - Gaussian Mixture Models:
        - Slides: lectures/unsupervised_learning/GMM/slides/GMM_slides.md
        - Notebook: lectures/unsupervised_learning/GMM/notebook/GMM_notebook.md
    - Spark:
      - Intro to Spark:
        - Slides: lectures/spark/intro_to_spark/intro_to_spark_slides.md
        - Notebook: lectures/spark/intro_to_spark/intro_to_spark_nb.md
      - Splink - Slides: lectures/spark/splink/splink_slides.md
    - Intro to Python:
      - Object Oriented Programming part 1:
        - Notebook: lectures/Intro_to_Python/oop/OOP_part1.md
      - Object Oriented Programming part 2:
        - Notebook: lectures/Intro_to_Python/oop/OOP_part2.md
      - Dynamic Programming:
        - Slides: lectures/Intro_to_Python/dynamic_programming/dynamic_programming_slides.md
        - Notebook: lectures/Intro_to_Python/dynamic_programming/dynamic_programming_notebook.md
  - Courses Taught:
    - Teaching Experiences: teaching_CV.md
    - Python for Data Science:
      - Syllabus: teaching/syllabi/ds542syllabus/ds542syllabus.pdf
    - Big Data Computing:
      - Syllabus: teaching/syllabi/DS610Syllabus/DS610SyllabusMaster_1_.docx.html
    - Advanced Programming for AI & Big Data:
      - Syllabus: teaching/syllabi/BDS4440_Syllabus/BDS4440_Syllabus.html
  - Scientific Conferences: conferences.md
  #- Real Estate: realestate/realestate.md
  #- Artwork/Sketches: art/artwork.md
  #- Writings:
  #  - A boy & the sea: writings/aboyandthesea.md
  #  - Facebook & Society: writings/facebook&society.md
  #  - Epigrams: writings/epigrams.md 